//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.DO.Objects
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categories", Namespace="http://schemas.datacontract.org/2004/07/Layers.DO.Objects")]
    public partial class Categories : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CategoryIDField;
        
        private string CategoryNameField;
        
        private string DescriptionField;
        
        private byte[] PictureField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture
        {
            get
            {
                return this.PictureField;
            }
            set
            {
                this.PictureField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICategories")]
public interface ICategories
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Insert", ReplyAction="http://tempuri.org/ICategories/InsertResponse")]
    void Insert(Layers.DO.Objects.Categories t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Insert", ReplyAction="http://tempuri.org/ICategories/InsertResponse")]
    System.Threading.Tasks.Task InsertAsync(Layers.DO.Objects.Categories t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Update", ReplyAction="http://tempuri.org/ICategories/UpdateResponse")]
    void Update(Layers.DO.Objects.Categories t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Update", ReplyAction="http://tempuri.org/ICategories/UpdateResponse")]
    System.Threading.Tasks.Task UpdateAsync(Layers.DO.Objects.Categories t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Delete", ReplyAction="http://tempuri.org/ICategories/DeleteResponse")]
    void Delete(Layers.DO.Objects.Categories t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Delete", ReplyAction="http://tempuri.org/ICategories/DeleteResponse")]
    System.Threading.Tasks.Task DeleteAsync(Layers.DO.Objects.Categories t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/GetAll", ReplyAction="http://tempuri.org/ICategories/GetAllResponse")]
    System.Collections.Generic.List<Layers.DO.Objects.Categories> GetAll();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/GetAll", ReplyAction="http://tempuri.org/ICategories/GetAllResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<Layers.DO.Objects.Categories>> GetAllAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICategoriesChannel : ICategories, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CategoriesClient : System.ServiceModel.ClientBase<ICategories>, ICategories
{
    
    public CategoriesClient()
    {
    }
    
    public CategoriesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CategoriesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CategoriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CategoriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Insert(Layers.DO.Objects.Categories t)
    {
        base.Channel.Insert(t);
    }
    
    public System.Threading.Tasks.Task InsertAsync(Layers.DO.Objects.Categories t)
    {
        return base.Channel.InsertAsync(t);
    }
    
    public void Update(Layers.DO.Objects.Categories t)
    {
        base.Channel.Update(t);
    }
    
    public System.Threading.Tasks.Task UpdateAsync(Layers.DO.Objects.Categories t)
    {
        return base.Channel.UpdateAsync(t);
    }
    
    public void Delete(Layers.DO.Objects.Categories t)
    {
        base.Channel.Delete(t);
    }
    
    public System.Threading.Tasks.Task DeleteAsync(Layers.DO.Objects.Categories t)
    {
        return base.Channel.DeleteAsync(t);
    }
    
    public System.Collections.Generic.List<Layers.DO.Objects.Categories> GetAll()
    {
        return base.Channel.GetAll();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<Layers.DO.Objects.Categories>> GetAllAsync()
    {
        return base.Channel.GetAllAsync();
    }
}
