//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.DO.Objects
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Suppliers", Namespace="http://schemas.datacontract.org/2004/07/Layers.DO.Objects")]
    public partial class Suppliers : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string CityField;
        
        private string CompanyNameField;
        
        private string ContactNameField;
        
        private string ContactTitleField;
        
        private string CountryField;
        
        private string FaxField;
        
        private string HomePageField;
        
        private string PhoneField;
        
        private string PostalCodeField;
        
        private string RegionField;
        
        private int SupplierIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactTitle
        {
            get
            {
                return this.ContactTitleField;
            }
            set
            {
                this.ContactTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePage
        {
            get
            {
                return this.HomePageField;
            }
            set
            {
                this.HomePageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierID
        {
            get
            {
                return this.SupplierIDField;
            }
            set
            {
                this.SupplierIDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISuppliers")]
public interface ISuppliers
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliers/Insert", ReplyAction="http://tempuri.org/ISuppliers/InsertResponse")]
    void Insert(Layers.DO.Objects.Suppliers t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliers/Insert", ReplyAction="http://tempuri.org/ISuppliers/InsertResponse")]
    System.Threading.Tasks.Task InsertAsync(Layers.DO.Objects.Suppliers t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliers/Update", ReplyAction="http://tempuri.org/ISuppliers/UpdateResponse")]
    void Update(Layers.DO.Objects.Suppliers t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliers/Update", ReplyAction="http://tempuri.org/ISuppliers/UpdateResponse")]
    System.Threading.Tasks.Task UpdateAsync(Layers.DO.Objects.Suppliers t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliers/Delete", ReplyAction="http://tempuri.org/ISuppliers/DeleteResponse")]
    void Delete(Layers.DO.Objects.Suppliers t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliers/Delete", ReplyAction="http://tempuri.org/ISuppliers/DeleteResponse")]
    System.Threading.Tasks.Task DeleteAsync(Layers.DO.Objects.Suppliers t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliers/GetAll", ReplyAction="http://tempuri.org/ISuppliers/GetAllResponse")]
    System.Collections.Generic.List<Layers.DO.Objects.Suppliers> GetAll();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuppliers/GetAll", ReplyAction="http://tempuri.org/ISuppliers/GetAllResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<Layers.DO.Objects.Suppliers>> GetAllAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISuppliersChannel : ISuppliers, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SuppliersClient : System.ServiceModel.ClientBase<ISuppliers>, ISuppliers
{
    
    public SuppliersClient()
    {
    }
    
    public SuppliersClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SuppliersClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SuppliersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SuppliersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Insert(Layers.DO.Objects.Suppliers t)
    {
        base.Channel.Insert(t);
    }
    
    public System.Threading.Tasks.Task InsertAsync(Layers.DO.Objects.Suppliers t)
    {
        return base.Channel.InsertAsync(t);
    }
    
    public void Update(Layers.DO.Objects.Suppliers t)
    {
        base.Channel.Update(t);
    }
    
    public System.Threading.Tasks.Task UpdateAsync(Layers.DO.Objects.Suppliers t)
    {
        return base.Channel.UpdateAsync(t);
    }
    
    public void Delete(Layers.DO.Objects.Suppliers t)
    {
        base.Channel.Delete(t);
    }
    
    public System.Threading.Tasks.Task DeleteAsync(Layers.DO.Objects.Suppliers t)
    {
        return base.Channel.DeleteAsync(t);
    }
    
    public System.Collections.Generic.List<Layers.DO.Objects.Suppliers> GetAll()
    {
        return base.Channel.GetAll();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<Layers.DO.Objects.Suppliers>> GetAllAsync()
    {
        return base.Channel.GetAllAsync();
    }
}
