//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.DO.Objects
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Products", Namespace="http://schemas.datacontract.org/2004/07/Layers.DO.Objects")]
    public partial class Products : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> CategoryIDField;
        
        private bool DiscontinuedField;
        
        private int ProductIDField;
        
        private string ProductNameField;
        
        private string QuantityPerUnitField;
        
        private System.Nullable<short> ReorderLevelField;
        
        private System.Nullable<int> SupplierIDField;
        
        private System.Nullable<decimal> UnitPriceField;
        
        private System.Nullable<short> UnitsInStockField;
        
        private System.Nullable<short> UnitsOnOrderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Discontinued
        {
            get
            {
                return this.DiscontinuedField;
            }
            set
            {
                this.DiscontinuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityPerUnit
        {
            get
            {
                return this.QuantityPerUnitField;
            }
            set
            {
                this.QuantityPerUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ReorderLevel
        {
            get
            {
                return this.ReorderLevelField;
            }
            set
            {
                this.ReorderLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SupplierID
        {
            get
            {
                return this.SupplierIDField;
            }
            set
            {
                this.SupplierIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> UnitsInStock
        {
            get
            {
                return this.UnitsInStockField;
            }
            set
            {
                this.UnitsInStockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> UnitsOnOrder
        {
            get
            {
                return this.UnitsOnOrderField;
            }
            set
            {
                this.UnitsOnOrderField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IProducts")]
public interface IProducts
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/Insert", ReplyAction="http://tempuri.org/IProducts/InsertResponse")]
    void Insert(Layers.DO.Objects.Products t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/Insert", ReplyAction="http://tempuri.org/IProducts/InsertResponse")]
    System.Threading.Tasks.Task InsertAsync(Layers.DO.Objects.Products t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/Update", ReplyAction="http://tempuri.org/IProducts/UpdateResponse")]
    void Update(Layers.DO.Objects.Products t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/Update", ReplyAction="http://tempuri.org/IProducts/UpdateResponse")]
    System.Threading.Tasks.Task UpdateAsync(Layers.DO.Objects.Products t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/Delete", ReplyAction="http://tempuri.org/IProducts/DeleteResponse")]
    void Delete(Layers.DO.Objects.Products t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/Delete", ReplyAction="http://tempuri.org/IProducts/DeleteResponse")]
    System.Threading.Tasks.Task DeleteAsync(Layers.DO.Objects.Products t);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/GetAll", ReplyAction="http://tempuri.org/IProducts/GetAllResponse")]
    System.Collections.Generic.List<Layers.DO.Objects.Products> GetAll();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/GetAll", ReplyAction="http://tempuri.org/IProducts/GetAllResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<Layers.DO.Objects.Products>> GetAllAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProductsChannel : IProducts, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProductsClient : System.ServiceModel.ClientBase<IProducts>, IProducts
{
    
    public ProductsClient()
    {
    }
    
    public ProductsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProductsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProductsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProductsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Insert(Layers.DO.Objects.Products t)
    {
        base.Channel.Insert(t);
    }
    
    public System.Threading.Tasks.Task InsertAsync(Layers.DO.Objects.Products t)
    {
        return base.Channel.InsertAsync(t);
    }
    
    public void Update(Layers.DO.Objects.Products t)
    {
        base.Channel.Update(t);
    }
    
    public System.Threading.Tasks.Task UpdateAsync(Layers.DO.Objects.Products t)
    {
        return base.Channel.UpdateAsync(t);
    }
    
    public void Delete(Layers.DO.Objects.Products t)
    {
        base.Channel.Delete(t);
    }
    
    public System.Threading.Tasks.Task DeleteAsync(Layers.DO.Objects.Products t)
    {
        return base.Channel.DeleteAsync(t);
    }
    
    public System.Collections.Generic.List<Layers.DO.Objects.Products> GetAll()
    {
        return base.Channel.GetAll();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<Layers.DO.Objects.Products>> GetAllAsync()
    {
        return base.Channel.GetAllAsync();
    }
}
